const assert = require("node:assert/strict");
const api = require("../skin/blog-editorial.js");
const catalog = require("../docs/catalog.json");
const posts = api.publicPosts(catalog);
assert.ok(posts.length > 0);
assert.equal(posts.length, catalog.posts.length);
const groups = new Set(posts.map(api.topic));
assert.equal([...groups].reduce((n, g) => n + api.selectPosts(posts, g, "", "latest").length, 0), posts.length);
for (const group of groups) assert.ok(api.selectPosts(posts, group, "", "latest").every(p => api.topic(p) === group));
assert.ok(api.selectPosts(posts, "", "UART", "latest").length > 0);
assert.deepEqual(api.selectPosts(posts, "", "UART", "latest"), api.selectPosts(posts, "", "uart", "latest"));
assert.ok(api.selectPosts(posts, "", "KV Cache", "latest").some(p => p.id === 124));
assert.deepEqual(api.selectPosts(posts, "", "zzzxmissingxzzz", "latest"), []);
assert.equal(api.publicPosts({posts: [posts[0], posts[0], {...posts[0],id:999,url:"javascript:alert(1)"}, null]}).length, 1);
const future = {...posts[0],id:900,url:"https://semicon-circuit.tistory.com/900",title:"Future",date:"2099-01-01"};
assert.equal(api.selectPosts([...posts,future],"","","latest")[0].id,900);
const backdated = {...future,id:901,url:"https://semicon-circuit.tistory.com/901",date:"2000-01-01"};
assert.notEqual(api.selectPosts([...posts,backdated],"","","latest")[0].id,901);
assert.equal(api.progressRatio(100,1000,0,400),0);
assert.equal(api.progressRatio(100,1000,400,400),0.5);
assert.equal(api.progressRatio(100,1000,2000,400),1);
assert.equal(api.progressRatio(100,100,0,400),0);
assert.equal(api.progressRatio(100,100,300,400),1);
assert.equal(api.categoryUrl('/category/반도체 시사'),'https://semicon-circuit.tistory.com/category/%EB%B0%98%EB%8F%84%EC%B2%B4%20%EC%8B%9C%EC%82%AC');
assert.equal(api.categoryUrl('/category'),'https://semicon-circuit.tistory.com/category');
assert.equal(api.categoryUrl('https://evil.example/category/test'),'');
assert.equal(api.categoryUrl('javascript:alert(1)'),'');
assert.equal(api.categoryUrl('/manage/posts/'),'');
assert.equal(api.categoryUrl('//evil.example/category/test'),'');
assert.ok(posts.every(p=>api.categoryUrl(p.categoryPath)));
const fs = require('node:fs');
const vm = require('node:vm');
const early = fs.readFileSync(require('node:path').join(__dirname,'../skin/editorial-head.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
function earlyState(pathname,search='') {
  const classes = new Set(); let timeout;
  vm.runInNewContext(early,{document:{documentElement:{classList:{add:(...n)=>n.forEach(x=>classes.add(x)),remove:n=>classes.delete(n),contains:n=>classes.has(n)}}},location:{pathname,search},URLSearchParams,setTimeout:f=>{timeout=f;}});
  return {classes,timeout};
}
let initial=earlyState('/'); assert.ok(initial.classes.has('sd-home-loading')); initial.timeout();
assert.ok(initial.classes.has('sd-home-fallback')); assert.ok(!initial.classes.has('sd-home-loading'));
initial=earlyState('/'); initial.classes.add('sd-home-active'); initial.timeout(); assert.ok(!initial.classes.has('sd-home-fallback'));
assert.ok(!earlyState('/','?page=2').classes.has('sd-home-loading'));
assert.ok(earlyState('/124').classes.has('sd-article-active'));
assert.ok(earlyState('/category/RTL').classes.has('sd-archive-active'));
assert.ok(!earlyState('/manage/posts/').classes.has('sd-article-active'));
console.log("PASS: editorial public-only catalog, all category filters, search, sorting, future posts, scroll bounds");
